language: rust
rust: nightly
sudo: required
services:
  - docker
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink gcc; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/versions/llvm38 homebrew/versions/gcc49 coreutils; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXX=$(which clang++-3.8); fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LLVM_CONFIG=$(which llvm-config-3.8); fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t afl.rs -f ci/Dockerfile .; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then RUN="docker run -t afl.rs"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then SL=/System/Library; PL=com.apple.ReportCrash; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then launchctl unload -w ${SL}/LaunchAgents/${PL}.plist; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo launchctl unload -w ${SL}/LaunchDaemons/${PL}.Root.plist; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then alias timeout=gtimeout; fi
script:
  - $RUN ./ci/run.sh
